site_name: Neuroglia Python Framework
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - 3-Minute Bootstrap: guides/3-min-bootstrap.md
    - Local Development Setup: guides/local-development.md
    - Mario's Pizzeria Tutorial: guides/mario-pizzeria-tutorial.md
  - Patterns:
    - Overview: patterns/index.md
    - Clean Architecture: patterns/clean-architecture.md
    - CQRS: patterns/cqrs.md
    - Event-Driven: patterns/event-driven.md
    - Repository: patterns/repository.md
    - Resource-Oriented Architecture: patterns/resource-oriented-architecture.md
    - Watcher & Reconciliation Patterns: patterns/watcher-reconciliation-patterns.md
    - Watcher & Reconciliation Execution: patterns/watcher-reconciliation-execution.md
  - Features:
    - Overview: features/index.md
    - Dependency Injection: features/dependency-injection.md
    - CQRS & Mediation: features/cqrs-mediation.md
    - MVC Controllers: features/mvc-controllers.md
    - Data Access: features/data-access.md
    - Event Sourcing: features/event-sourcing.md
    - Serialization: features/serialization.md
    - Object Mapping: features/object-mapping.md
    - Reactive Programming: features/reactive-programming.md
    - Background Task Scheduling: features/background-task-scheduling.md
    - Redis Cache Repository: features/redis-cache-repository.md
    - HTTP Service Client: features/http-service-client.md
    - Case Conversion Utilities: features/case-conversion-utilities.md
    - Enhanced Model Validation: features/enhanced-model-validation.md
    - Mermaid Diagrams: features/mermaid-diagrams.md
  - Guides:
    - Overview: guides/index.md
    - Project Setup: guides/project-setup.md
    - Testing Setup: guides/testing-setup.md
  - Sample Applications:
    - Overview: samples/index.md
    - OpenBank: samples/openbank.md
    - API Gateway: samples/api_gateway.md
    - Desktop Controller: samples/desktop_controller.md
    - Lab Resource Manager: samples/lab-resource-manager.md
  - Architecture: architecture.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mermaid2:
      arguments:
        theme: auto
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976d2'
          lineColor: '#1976d2'
          secondaryColor: '#f5f5f5'
          tertiaryColor: '#ffffff'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bvandewe/pyneuro