site_name: Neuroglia Python Framework
site_description: A lightweight, opinionated Python framework built on FastAPI that enforces clean architecture principles
site_url: https://bvandewe.github.io/pyneuro
docs_dir: docs
site_dir: site

repo_name: bvandewe/pyneuro
repo_url: https://github.com/bvandewe/pyneuro
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - 3-Minute Bootstrap: guides/3-min-bootstrap.md
    - Local Development Setup: guides/local-development.md
    - Mario's Pizzeria Tutorial: guides/mario-pizzeria-tutorial.md
  - Mario's Pizzeria:
    - Case Study Overview: mario-pizzeria.md
    - Business Analysis: mario-pizzeria/business-analysis.md
    - Technical Architecture: mario-pizzeria/technical-architecture.md
    - Domain Design: mario-pizzeria/domain-design.md
    - Implementation Guide: mario-pizzeria/implementation-guide.md
    - Testing & Deployment: mario-pizzeria/testing-deployment.md
  - Patterns:
    - patterns/index.md
    - Persistence Patterns: patterns/persistence-patterns.md
    - Unit of Work: patterns/unit-of-work.md
    - Pipeline Behaviors: patterns/pipeline-behaviors.md
    - Domain Driven Design: patterns/domain-driven-design.md
    - Repository Pattern: patterns/repository.md
    - Event-Driven Architecture: patterns/event-driven.md
  - Features:
    - features/index.md
    - Simple CQRS: features/simple-cqrs.md
    - MVC Controllers: features/mvc-controllers.md
    - Data Access: features/data-access.md
    - Object Mapping: features/object-mapping.md
    - Serialization: features/serialization.md
    - Enhanced Model Validation: features/enhanced-model-validation.md
    - Case Conversion Utilities: features/case-conversion-utilities.md
    - HTTP Service Client: features/http-service-client.md
    - Redis Cache Repository: features/redis-cache-repository.md
    - Background Task Scheduling: features/background-task-scheduling.md
    - Resilient Handler Discovery: features/resilient-handler-discovery.md
    - Configurable Type Discovery: features/configurable-type-discovery.md
    - Mermaid Diagrams: features/mermaid-diagrams.md
  - Guides:
    - Overview: guides/index.md
    - Project Setup: guides/project-setup.md
    - Testing Setup: guides/testing-setup.md
    - JsonSerializer Configuration: guides/jsonserializer-configuration.md
  - Samples:
    - Overview: samples/index.md
    - OpenBank: samples/openbank.md
    - API Gateway: samples/api_gateway.md
    - Desktop Controller: samples/desktop_controller.md
    # - Lab Resource Manager: samples/lab-resource-manager.md
  - References:
    - Persistence Documentation Guide: references/persistence-documentation-guide.md
    - OAuth, OIDC & JWT: references/oauth-oidc-jwt.md
    - Source Code Naming Conventions: references/source_code_naming_convention.md
    - 12-Factor App: references/12-factor-app.md
    - Python Typing Guide: references/python_typing_guide.md
    - Python Modular Code: references/python_modular_code.md
    - Python Object-Oriented Programming: references/python_object_oriented.md
    - Mermaid References: references/test-mermaid.md
    - AI Agent Instructions: ai-agent-guide.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mermaid2:
      arguments:
        theme: auto
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976d2'
          lineColor: '#1976d2'
          secondaryColor: '#f5f5f5'
          tertiaryColor: '#ffffff'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bvandewe/pyneuro
