site_name: Neuroglia Python Framework
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - 3-Minute Bootstrap: guides/3-min-bootstrap.md
    - Local Development Setup: guides/local-development.md
    - Mario's Pizzeria Tutorial: guides/mario-pizzeria-tutorial.md
  - Mario's Pizzeria:
    - Case Study Overview: mario-pizzeria.md
    - Business Analysis: mario-pizzeria/business-analysis.md
    - Technical Architecture: mario-pizzeria/technical-architecture.md
    - Domain Design: mario-pizzeria/domain-design.md
    - Implementation Guide: mario-pizzeria/implementation-guide.md
    - Testing & Deployment: mario-pizzeria/testing-deployment.md
  - Patterns:
    - Overview: patterns/index.md
    - Clean Architecture: patterns/clean-architecture.md
    - Domain Driven Design: patterns/domain-driven-design.md
    - Dependency Injection: patterns/dependency-injection.md
    - CQRS & Mediation: patterns/cqrs.md
    - Event-Driven: patterns/event-driven.md
    - Event Sourcing: patterns/event-sourcing.md
    - Reactive Programming: patterns/reactive-programming.md
    - Repository: patterns/repository.md
    - Resource-Oriented Architecture: patterns/resource-oriented-architecture.md
    - Watcher & Reconciliation Patterns: patterns/watcher-reconciliation-patterns.md
    - Watcher & Reconciliation Execution: patterns/watcher-reconciliation-execution.md
  - Features:
    - Overview: features/index.md
    - MVC Controllers: features/mvc-controllers.md
    - Data Access: features/data-access.md
    - Serialization: features/serialization.md
    - Configurable Type Discovery: features/configurable-type-discovery.md
    - Object Mapping: features/object-mapping.md
    - Background Task Scheduling: features/background-task-scheduling.md
    - Redis Cache Repository: features/redis-cache-repository.md
    - HTTP Service Client: features/http-service-client.md
    - Case Conversion Utilities: features/case-conversion-utilities.md
    - Enhanced Model Validation: features/enhanced-model-validation.md
    - Mermaid Diagrams: features/mermaid-diagrams.md
  - Guides:
    - Overview: guides/index.md
    - Project Setup: guides/project-setup.md
    - Testing Setup: guides/testing-setup.md
    - JsonSerializer Configuration: guides/jsonserializer-configuration.md
  - Samples:
    - Overview: samples/index.md
    - OpenBank: samples/openbank.md
    - API Gateway: samples/api_gateway.md
    - Desktop Controller: samples/desktop_controller.md
    # - Lab Resource Manager: samples/lab-resource-manager.md
  - References:
    - OAuth, OIDC & JWT: references/oauth-oidc-jwt.md
    - Source Code Naming Conventions: references/source_code_naming_convention.md
    - 12-Factor App: references/12-factor-app.md
    - Python Type Hints: references/python_type_hints.md
    - Python Modular Code: references/python_modular_code.md
    - Python Object-Oriented Programming: references/python_object_oriented.md
    - Python Generic Types: references/python_generic_types.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mermaid2:
      arguments:
        theme: auto
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976d2'
          lineColor: '#1976d2'
          secondaryColor: '#f5f5f5'
          tertiaryColor: '#ffffff'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bvandewe/pyneuro
