site_name: Neuroglia Python Framework
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Features:
    - Simple CQRS: features/simple-cqrs.md
    - Dependency Injection: features/dependency-injection.md
    - CQRS & Mediation: features/cqrs-mediation.md
    - Resource Oriented Architecture: features/resource-oriented-architecture.md
    - Watcher & Reconciliation Patterns: features/watcher-reconciliation-patterns.md
    - Watcher & Reconciliation Execution: features/watcher-reconciliation-execution.md
    - MVC Controllers: features/mvc-controllers.md
    - Data Access: features/data-access.md
    - Event Sourcing: features/event-sourcing.md
    - Mermaid Diagrams: features/mermaid-diagrams.md
    - Event Handling: features/event-handling.md
    - Object Mapping: features/object-mapping.md
    - Configuration: features/configuration.md
    - Hosting: features/hosting.md
    - Core: features/core.md
    - Serialization: features/serialization.md
  - Sample Applications:
    - OpenBank: samples/openbank.md
    - Lab Resource Manager: samples/lab-resource-manager.md
    - API Gateway: samples/api_gateway.md
    - Desktop Controller: samples/desktop_controller.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mermaid2:
      arguments:
        theme: auto
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976d2'
          lineColor: '#1976d2'
          secondaryColor: '#f5f5f5'
          tertiaryColor: '#ffffff'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bvandewe/pyneuro