# Production-Ready Log Integration for Mario's Pizzeria
# This extends docker-compose.mario.yml with Loki logging integration

name: mario-pizzeria
services:
  # 🍕 Mario's Pizzeria Application with Loki Logging
  mario-pizzeria-app:
    image: mario-pizzeria-app
    build:
      context: ../.. # Build from project root
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "cd samples/mario-pizzeria && PYTHONPATH=/app/src:/app/samples/mario-pizzeria python -m uvicorn main:app --host 0.0.0.0 --port 8080",
      ]
    ports:
      - 8080:8080
    environment:
      LOCAL_DEV: true
      LOG_LEVEL: DEBUG
      PYTHONPATH: "src"
      CONNECTION_STRINGS: '{"mongo": "mongodb://root:mario123@mongodb:27017/?authSource=admin", "eventstore": "esdb://eventstoredb:2113?Tls=false"}'
      CLOUD_EVENT_SINK: http://event-player:8080/events/pub
      CLOUD_EVENT_SOURCE: https://mario-pizzeria.io
      CLOUD_EVENT_TYPE_PREFIX: io.mario-pizzeria
      # OpenTelemetry configuration
      OTEL_RESOURCE_ATTRIBUTES: "service.name=mario-pizzeria,service.version=1.0.0"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
    networks:
      - mario-net
    depends_on:
      - mongodb
      - eventstoredb
      - loki
      - tempo
      - prometheus
    # Configure Docker to send logs directly to Loki
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-labels: "service=mario-pizzeria,environment=development"
        # Optional: Include container metadata
        loki-external-labels: "container_name={{.Name}},image_name={{.ImageName}}"

  # 📊 Promtail - Production Log Shipping Agent (Alternative approach)
  promtail:
    image: grafana/promtail:latest
    container_name: mario-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - mario-net
    depends_on:
      - loki
    profiles:
      - promtail # Enable with: docker-compose --profile promtail up

  # All other services inherit from main docker-compose.mario.yml
  # Just add this file to enable Loki logging:
  # docker-compose -f docker-compose.mario.yml -f docker-compose.mario-loki.yml up

networks:
  mario-net:
    driver: bridge

volumes:
  mongodb-data:
  eventstore-data:
  eventstoredb-data:
  grafana-storage:
  prometheus-data:
